{ pkgs, inputs, ... }:
{
  environment.systemPackages = with pkgs; [
    wget
    prismlauncher
    obsidian
    spotify
    btop
    alacritty
    gparted
    fastfetch
    ffmpeg-full
    mangohud
    vlc
    syncthing
    syncthingtray
    protonplus
    javaPackages.compiler.temurin-bin.jre-17
    qbittorrent
    xwayland-satellite
    wl-clipboard
    wlr-randr
    brightnessctl
    cliphist
    gamescope
    kdePackages.breeze
    nautilus
    loupe
    file-roller
    gnome.gvfs
    adwaita-icon-theme
    gnome-calculator
    gnome-text-editor
    papers
    fd
    proton-authenticator
    element-desktop
    balatro-mod-manager
    blender
    playerctl
    nixd
    devenv
    libsecret
    satisfactorymodmanager
    gcr
    seahorse
    inputs.hytale-launcher.packages.x86_64-linux.default
  ];
}